### ISSUE TITLE
6.1 - As a pharmacy worker I want to be able to find information about specific meds so that I can make information available to customers 

### ISSUE THREAD

**Issue by betsygrantham** [ConnerOzenne/Rapid-Rx#14]
Given a worker wants to find information on a specific medication, when they click on that medicine, they are taken to a page where more information is displayed
Given a worker wants to find info on a specific medication, when they search the medicine page there are pictures of each medicine next to its name for reference

**Comment by mplennon617** [comment]
Closed, pending inclusion of pictures
