### ISSUE TITLE
6.2 - As a pharmacy worker I want to be able to edit a specific medicine's profile so that I can make information available to customers 

### ISSUE THREAD

**Issue by betsygrantham** [ConnerOzenne/Rapid-Rx#16]
Given a worker wants to add information about a specific medication, when they click on the medicine and are taken to that med's page, there is an 'edit info' button allowing them to edit the page and med information

Given a worker wants to change a med's picture, when they click on the medicine and go to that medicine's page, there is an edit picture button allowing them to do so

**Comment by mplennon617** [comment]
Closed, pending posting back to the database and usage of images.
