### ISSUE TITLE
5.3 - As a customer I want to be able to know what my meds should not be taken with So that I refresh my memory on what not to have with my meds

### ISSUE THREAD

**Issue by Chithom** [ConnerOzenne/Rapid-Rx#17]
Given a customer has an account, when they look at their meds, then they can read about what other meds or food not to have with their meds.
given a user wants to look up a medication, when they go the med list, then they can look up meds to see what other food or meds affect the looked up med.

**Comment by mplennon617** [comment]
Almost done
