### ISSUE TITLE
3.1 - As a pharmacy worker I want to view current prescriptions for my location so that I can get an overview of what meds are being taken by my customers

### ISSUE THREAD

**Issue by mplennon617** [ConnerOzenne/Rapid-Rx#2]
Given a worker wants an overview of all prescription currently being filled, when they navigate to the location summary page they can see it 

Given a pharmacy worker is not logged in, when they navigate to the pharmacy location summary page, they are asked to sign in

**Comment by mplennon617** [comment]
Almost Done

**Comment by mitchmorrison2** [comment]
Order history is by location and shows the pharmacist the user, medication, date ordered, etc.
