### ISSUE TITLE
5.4 - As a customer I want to be able to save a meds page on my account so that I can have an easier path to get to it

### ISSUE THREAD

**Issue by Chithom** [ConnerOzenne/Rapid-Rx#23]
Given a customer wants to add a medication's info, when they flag a medication, they then see it marked on their account page as link to a med that they are not taking.
Given a pharmacy worker wants to show a customer a medication, when they look at the customer's account they can, then flag it to be shown on the customer's account as info.

**Comment by mplennon617** [comment]
Flag button on homepage >> show flagged items on profile >> will link to MedInfo/:medId (Betsy's "More Info" page)

Figure this out once flagging is done on the homepage
