### ISSUE TITLE
7.3 I want to be able to see the prescription the doctor has wrote	So that I can pick the prescription up

### ISSUE THREAD

**Issue by Edward-jiang495** [ConnerOzenne/Rapid-Rx#25]
Given the user didn't visit the doctor, the site would simply show a list of prescription history that user has on the site. The list would be from newest to oldest, the prescription that hasn't been picked up would be the first. The site would then allow the user to pick on the prescription and pick a location for pick up. | Given that the user has visit a doctor or a doctor has written a prescription for the user, the site would also show a list of prescription history, but also with details about the visit/doctor. And it would also allow the user to pick on the prescription and pick a location for pick up
-- | --

**Comment by mplennon617** [comment]
You will pick up from your Home Pharmacy

Will look into Doctor (Pharmacy Worker) interaction later
