### ISSUE TITLE
6.3 - As a pharmacy worker I want to be able to flag certain medicines for certain actions so that I can make information available to customers 

### ISSUE THREAD

**Issue by betsygrantham** [ConnerOzenne/Rapid-Rx#26]
Given a worker wants to flag or favorite a specific med (bestseller, sold out, recalled, etc), there is a flag or favorite button next to the medicine that causes it to be flagged.
Given a worker wants to order more of a product, when you click on the medicine there is an 'order more' button

**Comment by mplennon617** [comment]
Generalized to all users, not just pharmacy workers
