### ISSUE TITLE
3.2 - As a pharmacy worker I want to view past prescriptions for my location so that I can gauge what amounts I will need to order for the future

### ISSUE THREAD

**Issue by mplennon617** [ConnerOzenne/Rapid-Rx#3]
Given a worker wants to estimate how many prescriptions they will need to order for the future, when they navigate to the summary page and check show previous prescriptions then they can see them all 

Given a pharmacy worker is not logged in, when they navigate to the pharmacy location summary page, they are asked to sign in

**Comment by mplennon617** [comment]
Almost done

**Comment by mitchmorrison2** [comment]
Completed, on pharmacyPortal page with order history
