### ISSUE TITLE
3.3 - As a pharmacy worker I want to be able to see all lifetime prescriptions provided so that I can know information about store stats

### ISSUE THREAD

**Issue by mplennon617** [ConnerOzenne/Rapid-Rx#4]
Given a worker wants to generate stats about which prescriptions are most used for corporate , when they navigate to the summary page then they can get totals and other stats 

Given a pharmacy worker is not logged in, when they navigate to the pharmacy location summary page, they are asked to sign in

**Comment by mitchmorrison2** [comment]
Finished with pharmacyPortal page
