### ISSUE TITLE
3.4 - As a pharmacy worker I want to be able to compare current inventory to all prescriptions that will need to be refilled in the next month so that I can gauge what amounts I will need to order for the future

### ISSUE THREAD

**Issue by mplennon617** [ConnerOzenne/Rapid-Rx#5]
Given a worker wants to order upcoming prescriptions, when they look at orders in the next month then they can easily see what they will need to get 

Given a pharmacy worker is not logged in, when they navigate to the pharmacy location summary page, they are asked to sign in

**Comment by mplennon617** [comment]
Likely rejection

**Comment by mitchmorrison2** [comment]
With order history, it is possible to view all the previous orders and use this information to predict future orders.
