### ISSUE TITLE
4.2 - As a pharmacy worker I want to be able to mark or unmark a medication to be ordered so that I can have a list to then order

### ISSUE THREAD

**Issue by mplennon617** [ConnerOzenne/Rapid-Rx#7]
Given a pharmacy worker is logged in, when they click on a medication, then they can choose to mark it for order and have it added to a list 

Given a pharmacy worker is logged in, when they click on a medication, then they can choose to unmark it for order and have it removed from the order list

**Comment by mplennon617** [comment]
Rejecting "Shopping Cart" functionality for the time being

**Comment by ConnerOzenne** [comment]
Implemented stock updating differently
